export default {
  "GET_TODO_LIST_START": "todo/GET_TODO_LIST_START",
  "GET_TODO_LIST_SUCCESS": "todo/GET_TODO_LIST_SUCCESS",
  "GET_TODO_LIST_FAILURE": "todo/GET_TODO_LIST_FAILURE",

  "ADD_TODO_START": "todo/ADD_TODO_START",
  "ADD_TODO_SUCCESS": "todo/ADD_TODO_SUCCESS",
  "ADD_TODO_FAILURE": "todo/ADD_TODO_FAILURE",

  "CHANGE_COMPLETED_STATUS_IN_TODO_START":
    "todo/CHANGE_COMPLETED_STATUS_IN_TODO_START",
  "CHANGE_COMPLETED_STATUS_IN_TODO_SUCCESS":
    "todo/CHANGE_COMPLETED_STATUS_IN_TODO_SUCCESS",
  "CHANGE_COMPLETED_STATUS_IN_TODO_FAILURE":
    "todo/CHANGE_COMPLETED_STATUS_IN_TODO_FAILURE",

  "REMOVE_TODO_START": "todo/REMOVE_TODO_START",
  "REMOVE_TODO_SUCCESS": "todo/REMOVE_TODO_SUCCESS",
  "REMOVE_TODO_FAILURE": "todo/REMOVE_TODO_FAILURE",

  "CHANGE_FILTER_STATUS": "todo/CHANGE_FILTER_STATUS",
};
