export default {
  GET_ITEMS_START: "items/GET_ITEMS_START",
  GET_ITEMS_SUCCESS: "items/GET_ITEMS_SUCCESS",
  GET_ITEMS_FAILURE: "items/GET_ITEMS_FAILURE",

  ADD_ITEM_START: "items/ADD_ITEM_START",
  ADD_ITEM_SUCCESS: "items/ADD_ITEM_SUCCESS",
  ADD_ITEM_FAILURE: "items/ADD_ITEM_FAILURE",

  CHANGE_COMPLETED_STATUS_IN_ITEM_START:
    "items/CHANGE_COMPLETED_STATUS_IN_ITEM_START",
  CHANGE_COMPLETED_STATUS_IN_ITEM_SUCCESS:
    "items/CHANGE_COMPLETED_STATUS_IN_ITEM_SUCCESS",
  CHANGE_COMPLETED_STATUS_IN_ITEM_FAILURE:
    "items/CHANGE_COMPLETED_STATUS_IN_ITEM_FAILURE",

  REMOVE_ITEM_START: "items/REMOVE_ITEM_START",
  REMOVE_ITEM_SUCCESS: "items/REMOVE_ITEM_SUCCESS",
  REMOVE_ITEM_FAILURE: "items/REMOVE_ITEM_FAILURE",

  CHANGE_FILTER_STATUS: "items/CHANGE_FILTER_STATUS",
};
